In [1]:
import pandas as pd
import numpy as np
import sklearn
import matplotlib
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
URL = "https://raw.githubusercontent.com/ageron/handson-ml/refs/heads/master/datasets/housing/housing.csv"
df = pd.read_csv(URL)
df.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,median_house_value,ocean_proximity
0,-122.23,37.88,41.0,880.0,129.0,322.0,126.0,8.3252,452600.0,NEAR BAY
1,-122.22,37.86,21.0,7099.0,1106.0,2401.0,1138.0,8.3014,358500.0,NEAR BAY
2,-122.24,37.85,52.0,1467.0,190.0,496.0,177.0,7.2574,352100.0,NEAR BAY
3,-122.25,37.85,52.0,1274.0,235.0,558.0,219.0,5.6431,341300.0,NEAR BAY
4,-122.25,37.85,52.0,1627.0,280.0,565.0,259.0,3.8462,342200.0,NEAR BAY

In [3]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=35)

In [4]:
housing = train_set.drop("median_house_value", axis=1)
housing_labels = train_set["median_house_value"].copy()

## 1. NaN values

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object
dtypes: float64(9), object(1)
memory usage: 1.6+ MB

In [6]:
housing.dropna(subset=["total_bedrooms"])

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income,ocean_proximity
1380,-122.09,38.00,6.0,10191.0,1882.0,4377.0,1789.0,5.2015,NEAR BAY
12294,-116.93,33.93,13.0,7804.0,1594.0,3297.0,1469.0,2.0549,INLAND
7387,-118.25,33.97,37.0,794.0,210.0,814.0,213.0,2.2917,<1H OCEAN
14454,-117.27,32.83,39.0,1877.0,426.0,805.0,409.0,3.8750,NEAR OCEAN
2927,-119.01,35.36,24.0,1941.0,484.0,1277.0,435.0,1.0560,INLAND
...,...,...,...,...,...,...,...,...,...
15808,-122.44,37.76,52.0,2509.0,496.0,855.0,478.0,5.0731,NEAR BAY
15393,-116.90,33.22,11.0,4132.0,773.0,2012.0,703.0,3.1906,<1H OCEAN
9143,-117.96,34.48,32.0,1896.0,342.0,806.0,299.0,4.5769,INLAND
17679,-121.84,37.32,22.0,3015.0,581.0,2491.0,530.0,4.3419,<1H OCEAN
5833,-118.32,34.20,36.0,1978.0,337.0,834.0,311.0,3.9866,<1H OCEAN

In [7]:
housing.drop("total_bedrooms", axis=1)

,longitude,latitude,housing_median_age,total_rooms,population,households,median_income,ocean_proximity
1380,-122.09,38.00,6.0,10191.0,4377.0,1789.0,5.2015,NEAR BAY
12294,-116.93,33.93,13.0,7804.0,3297.0,1469.0,2.0549,INLAND
7387,-118.25,33.97,37.0,794.0,814.0,213.0,2.2917,<1H OCEAN
14454,-117.27,32.83,39.0,1877.0,805.0,409.0,3.8750,NEAR OCEAN
2927,-119.01,35.36,24.0,1941.0,1277.0,435.0,1.0560,INLAND
...,...,...,...,...,...,...,...,...
19391,-120.85,37.78,25.0,421.0,303.0,106.0,2.2679,INLAND
15393,-116.90,33.22,11.0,4132.0,2012.0,703.0,3.1906,<1H OCEAN
9143,-117.96,34.48,32.0,1896.0,806.0,299.0,4.5769,INLAND
17679,-121.84,37.32,22.0,3015.0,2491.0,530.0,4.3419,<1H OCEAN
5833,-118.32,34.20,36.0,1978.0,834.0,311.0,3.9866,<1H OCEAN

In [8]:
# replacing nan
median = housing["total_bedrooms"].median()
median

np.float64(434.0)

In [9]:
housing["total_bedrooms"].fillna(median)

1380     1882.0
12294    1594.0
7387      210.0
14454     426.0
2927      484.0
          ...
19391     434.0
15393     773.0
9143      342.0
17679     581.0
5833      337.0
Name: total_bedrooms, Length: 16512, dtype: float64

## 2. Replacing NaN

### SimpleImputer

In [10]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(strategy="median")

In [11]:
imputer.fit(housing)

ValueError: Cannot use median strategy with non-numeric data:
could not convert string to float: 'NEAR BAY'

In [12]:
housing_num = housing.drop("ocean_proximity", axis=1)
housing_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
1380,-122.09,38.00,6.0,10191.0,1882.0,4377.0,1789.0,5.2015
12294,-116.93,33.93,13.0,7804.0,1594.0,3297.0,1469.0,2.0549
7387,-118.25,33.97,37.0,794.0,210.0,814.0,213.0,2.2917
14454,-117.27,32.83,39.0,1877.0,426.0,805.0,409.0,3.8750
2927,-119.01,35.36,24.0,1941.0,484.0,1277.0,435.0,1.0560
...,...,...,...,...,...,...,...,...
19391,-120.85,37.78,25.0,421.0,NaN,303.0,106.0,2.2679
15393,-116.90,33.22,11.0,4132.0,773.0,2012.0,703.0,3.1906
9143,-117.96,34.48,32.0,1896.0,342.0,806.0,299.0,4.5769
17679,-121.84,37.32,22.0,3015.0,581.0,2491.0,530.0,4.3419
5833,-118.32,34.20,36.0,1978.0,337.0,834.0,311.0,3.9866

In [13]:
imputer.fit(housing_num)

SimpleImputer(strategy='median')

In [14]:
imputer.statistics_

array([-118.495 ,   34.26  ,   29.    , 2120.5   ,  434.    , 1168.5   ,
        408.    ,    3.5338])

In [15]:
x = imputer.transform(housing_num)
x

array([[-1.2209e+02,  3.8000e+01,  6.0000e+00, ...,  4.3770e+03,
         1.7890e+03,  5.2015e+00],
       [-1.1693e+02,  3.3930e+01,  1.3000e+01, ...,  3.2970e+03,
         1.4690e+03,  2.0549e+00],
       [-1.1825e+02,  3.3970e+01,  3.7000e+01, ...,  8.1400e+02,
         2.1300e+02,  2.2917e+00],
       ...,
       [-1.1796e+02,  3.4480e+01,  3.2000e+01, ...,  8.0600e+02,
         2.9900e+02,  4.5769e+00],
       [-1.2184e+02,  3.7320e+01,  2.2000e+01, ...,  2.4910e+03,
         5.3000e+02,  4.3419e+00],
       [-1.1832e+02,  3.4200e+01,  3.6000e+01, ...,  8.3400e+02,
         3.1100e+02,  3.9866e+00]], shape=(16512, 8))

In [16]:
x = imputer.fit_transform(housing_num)

In [17]:
housing_tr = pd.DataFrame(x, columns=housing_num.columns, index=housing_num.index)
housing_tr.head()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
1380,-122.09,38.00,6.0,10191.0,1882.0,4377.0,1789.0,5.2015
12294,-116.93,33.93,13.0,7804.0,1594.0,3297.0,1469.0,2.0549
7387,-118.25,33.97,37.0,794.0,210.0,814.0,213.0,2.2917
14454,-117.27,32.83,39.0,1877.0,426.0,805.0,409.0,3.8750
2927,-119.01,35.36,24.0,1941.0,484.0,1277.0,435.0,1.0560

## 3. Text. SimpleEncoder & OrdinalEncoder

In [18]:
housing_cat = housing[["ocean_proximity"]]
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7313
INLAND             5218
NEAR OCEAN         2110
NEAR BAY           1866
ISLAND                5
Name: count, dtype: int64

In [19]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
housing_cat_encoded = ordinal_encoder.fit_transform(housing_cat)
housing_cat_encoded[:10]

array([[3.],
       [1.],
       [0.],
       [4.],
       [1.],
       [1.],
       [1.],
       [0.],
       [0.],
       [1.]])

In [24]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
housing_cat_1hot = cat_encoder.fit_transform(housing_cat)
housing_cat_1hot.toarray()

array([[0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       ...,
       [0., 1., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], shape=(16512, 5))

In [22]:
housing_cat.value_counts()

ocean_proximity
<1H OCEAN          7313
INLAND             5218
NEAR OCEAN         2110
NEAR BAY           1866
ISLAND                5
Name: count, dtype: int64

In [23]:
housing_cat

      ocean_proximity
1380         NEAR BAY
12294          INLAND
7387        <1H OCEAN
14454      NEAR OCEAN
2927           INLAND
...               ...
19391          INLAND
15393       <1H OCEAN
9143           INLAND
17679       <1H OCEAN
5833        <1H OCEAN

[16512 rows x 1 columns]

In [25]:
housing_onehot = pd.get_dummies(housing['ocean_proximity'])
housing_onehot

       <1H OCEAN  INLAND  ISLAND  NEAR BAY  NEAR OCEAN
1380       False   False   False      True       False
12294      False    True   False     False       False
7387        True   False   False     False       False
14454      False   False   False     False        True
2927       False    True   False     False       False
...          ...     ...     ...       ...         ...
19391      False    True   False     False       False
15393       True   False   False     False       False
9143       False    True   False     False       False
17679       True   False   False     False       False
5833        True   False   False     False       False

[16512 rows x 5 columns]

## 4. Custom Transformers

In [26]:
from sklearn.base import BaseEstimator, TransformerMixin

rooms_ix, bedrooms_ix, population_ix, households_ix = 3, 4, 5, 6

class CombinedAttributesAdder(BaseEstimator, TransformerMixin):
    def __init__(self, add_bedrooms_per_room = True): # no *args or **kargs
        self.add_bedrooms_per_room = add_bedrooms_per_room
    def fit(self, X, y=None):
        return self # nothing else to do
    def transform(self, X, y=None):
        rooms_per_household = X[:, rooms_ix] / X[:, households_ix]
        population_per_household = X[:, population_ix] / X[:, households_ix]
        if self.add_bedrooms_per_room:
            bedrooms_per_room = X[:, bedrooms_ix] / X[:, rooms_ix]
            return np.c_[X, rooms_per_household, population_per_household,
                         bedrooms_per_room]
        else:
            return np.c_[X, rooms_per_household, population_per_household]

In [ ]:
attr_adder = CombinedAttributesAdder(add_bedrooms_per_room=False)
housing_extra_attribs = attr_adder.transform(housing.values)

## 5. Normalization

In [27]:
housing.describe()

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
count,16512.000000,16512.000000,16512.000000,16512.000000,16346.000000,16512.000000,16512.000000,16512.000000
mean,-119.572816,35.635180,28.581335,2634.711967,537.338676,1428.578307,499.190286,3.870252
std,2.007532,2.135189,12.599434,2197.525936,423.459102,1144.987836,383.786586,1.906476
min,-124.350000,32.540000,1.000000,2.000000,1.000000,3.000000,1.000000,0.499900
25%,-121.800000,33.930000,18.000000,1444.000000,295.000000,786.000000,279.000000,2.562500
50%,-118.495000,34.260000,29.000000,2120.500000,434.000000,1168.500000,408.000000,3.533800
75%,-118.010000,37.720000,37.000000,3143.000000,646.000000,1728.000000,603.000000,4.738700
max,-114.310000,41.950000,52.000000,39320.000000,6445.000000,35682.000000,6082.000000,15.000100

In [28]:
from sklearn.preprocessing import MinMaxScaler

min_max_scaler = MinMaxScaler()

min_max_scaler.fit_transform(housing_num)

array([[0.2250996 , 0.58023379, 0.09803922, ..., 0.12259312, 0.29403059,
        0.3242438 ],
       [0.73904382, 0.1477152 , 0.23529412, ..., 0.09232322, 0.24140766,
        0.1072399 ],
       [0.60756972, 0.15196599, 0.70588235, ..., 0.02273046, 0.03486269,
        0.12357071],
       ...,
       [0.63645418, 0.20616366, 0.60784314, ..., 0.02250624, 0.0490051 ,
        0.28116854],
       [0.25      , 0.50797024, 0.41176471, ..., 0.0697329 , 0.08699227,
        0.26496186],
       [0.60059761, 0.17640808, 0.68627451, ..., 0.02329101, 0.05097846,
        0.24045875]], shape=(16512, 8))

In [29]:
housing_num

,longitude,latitude,housing_median_age,total_rooms,total_bedrooms,population,households,median_income
1380,-122.09,38.00,6.0,10191.0,1882.0,4377.0,1789.0,5.2015
12294,-116.93,33.93,13.0,7804.0,1594.0,3297.0,1469.0,2.0549
7387,-118.25,33.97,37.0,794.0,210.0,814.0,213.0,2.2917
14454,-117.27,32.83,39.0,1877.0,426.0,805.0,409.0,3.8750
2927,-119.01,35.36,24.0,1941.0,484.0,1277.0,435.0,1.0560
...,...,...,...,...,...,...,...,...
19391,-120.85,37.78,25.0,421.0,NaN,303.0,106.0,2.2679
15393,-116.90,33.22,11.0,4132.0,773.0,2012.0,703.0,3.1906
9143,-117.96,34.48,32.0,1896.0,342.0,806.0,299.0,4.5769
17679,-121.84,37.32,22.0,3015.0,581.0,2491.0,530.0,4.3419
5833,-118.32,34.20,36.0,1978.0,337.0,834.0,311.0,3.9866

## 6. Standardization

In [30]:
from sklearn.preprocessing import StandardScaler
standard_scaler = StandardScaler()
standard_scaler.fit_transform(housing_num)

array([[-1.25390838,  1.10757958, -1.79230424, ...,  2.57514612,
         3.36084902,  0.69829788],
       [ 1.31649014, -0.79863258, -1.2367069 , ...,  1.63187609,
         2.52702704, -0.9522322 ],
       [ 0.65894633, -0.77989831,  0.66819829, ..., -0.53677157,
        -0.74572422, -0.82802018],
       ...,
       [ 0.80340671, -0.54103634,  0.27134305, ..., -0.54375875,
        -0.52163456,  0.37066771],
       [-1.12937357,  0.78909696, -0.52236745, ...,  0.92791716,
         0.08028068,  0.24739988],
       [ 0.62407658, -0.67217624,  0.58882724, ..., -0.51930361,
        -0.49036624,  0.0610294 ]], shape=(16512, 8))